// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using covid_portal_api.infrastructure.Data;

namespace covid_portal_api.infrastructure.Migrations
{
    [DbContext(typeof(CovidContext))]
    partial class CovidContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("covid_portal_api.domain.Entities.Case", b =>
                {
                    b.Property<Guid>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CaseDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("NewConfirmed")
                        .HasColumnType("bigint");

                    b.Property<long>("NewDeaths")
                        .HasColumnType("bigint");

                    b.Property<long>("NewRecovered")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalConfirmed")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDeaths")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalRecovered")
                        .HasColumnType("bigint");

                    b.HasKey("CaseId");

                    b.HasIndex("CountryId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("covid_portal_api.domain.Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("covid_portal_api.domain.Entities.Case", b =>
                {
                    b.HasOne("covid_portal_api.domain.Entities.Country", "Country")
                        .WithMany("Cases")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("covid_portal_api.domain.Entities.Country", b =>
                {
                    b.Navigation("Cases");
                });
#pragma warning restore 612, 618
        }
    }
}
